Repository kakao-tech-campus-3rd-step3/Team15_BE, pull requests merged in 2025-09, with the labels that each got.

#12 feat: 게시글 검색/페이지네이션/통계 API 추가
  .gitignore
  build.gradle
  src/main/java/katecam/hyuswim/post/controller/PostController.java
  src/main/java/katecam/hyuswim/post/controller/PostStatController.java
  src/main/java/katecam/hyuswim/post/dto/PageResponse.java
  src/main/java/katecam/hyuswim/post/dto/PostSearchRequest.java
  src/main/java/katecam/hyuswim/post/dto/PostStatsResponse.java
  src/main/java/katecam/hyuswim/post/repository/PostRepository.java
  src/main/java/katecam/hyuswim/post/service/PostService.java
  src/main/java/katecam/hyuswim/post/service/PostStatService.java
Labels: feature

#22 [Bug] GitHub Actions 배포 중 프로세스 종료 시 워크플로우 실패
  .github/workflows/deploy.yml
Labels: bug

#24 refactor: dto 꼭필요한 어노테이션만 사용하게 변경
  src/main/java/katecam/hyuswim/post/dto/PostDetailResponse.java
  src/main/java/katecam/hyuswim/post/dto/PostListResponse.java
  src/main/java/katecam/hyuswim/user/User.java
  src/main/java/katecam/hyuswim/user/controller/UserController.java
  src/main/java/katecam/hyuswim/user/dto/JwtTokenRequest.java
  src/main/java/katecam/hyuswim/user/dto/JwtTokenResponse.java
  src/main/java/katecam/hyuswim/user/dto/LoginRequest.java
  src/main/java/katecam/hyuswim/user/dto/SignupRequest.java
  src/main/java/katecam/hyuswim/user/jwt/JwtUtil.java
  src/main/java/katecam/hyuswim/user/repository/UserRepository.java
  src/main/java/katecam/hyuswim/user/service/UserService.java
Labels: refactor

#32 chore : 코드 스타일 설정 추가 및 Spotless 포맷팅 적용
  .editorconfig
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/katecam/hyuswim/HyuswimApplication.java
  src/main/java/katecam/hyuswim/badge/Badge.java
  src/main/java/katecam/hyuswim/badge/BadgeType.java
  src/main/java/katecam/hyuswim/comment/Comment.java
  src/main/java/katecam/hyuswim/common/error/CustomException.java
  src/main/java/katecam/hyuswim/common/error/ErrorCode.java
  src/main/java/katecam/hyuswim/common/error/ErrorResponse.java
  src/main/java/katecam/hyuswim/common/error/GlobalExceptionHandler.java
  src/main/java/katecam/hyuswim/config/LocalSecurityConfig.java
  src/main/java/katecam/hyuswim/like/Like.java
  src/main/java/katecam/hyuswim/mission/Mission.java
  src/main/java/katecam/hyuswim/mission/progress/MissionProgress.java
  src/main/java/katecam/hyuswim/notification/NotiType.java
  src/main/java/katecam/hyuswim/notification/Notification.java
  src/main/java/katecam/hyuswim/post/controller/PostController.java
  src/main/java/katecam/hyuswim/post/controller/PostStatController.java
  src/main/java/katecam/hyuswim/post/domain/Post.java
  src/main/java/katecam/hyuswim/post/domain/PostCategory.java
  src/main/java/katecam/hyuswim/post/dto/PageResponse.java
  src/main/java/katecam/hyuswim/post/dto/PostDetailResponse.java
  src/main/java/katecam/hyuswim/post/dto/PostListResponse.java
  src/main/java/katecam/hyuswim/post/dto/PostRequest.java
  src/main/java/katecam/hyuswim/post/dto/PostSearchRequest.java
  src/main/java/katecam/hyuswim/post/dto/PostStatsResponse.java
  src/main/java/katecam/hyuswim/post/repository/PostRepository.java
  src/main/java/katecam/hyuswim/post/service/PostService.java
  src/main/java/katecam/hyuswim/post/service/PostStatService.java
  src/main/java/katecam/hyuswim/report/ReasonType.java
  src/main/java/katecam/hyuswim/report/Report.java
  src/main/java/katecam/hyuswim/report/ReportType.java
  src/main/java/katecam/hyuswim/support/Support.java
  src/main/java/katecam/hyuswim/support/SupportType.java
  src/main/java/katecam/hyuswim/user/User.java
  src/main/java/katecam/hyuswim/user/UserRole.java
  src/main/java/katecam/hyuswim/user/controller/UserController.java
  src/main/java/katecam/hyuswim/user/dto/JwtTokenRequest.java
  src/main/java/katecam/hyuswim/user/dto/JwtTokenResponse.java
  src/main/java/katecam/hyuswim/user/dto/LoginRequest.java
  src/main/java/katecam/hyuswim/user/dto/SignupRequest.java
  src/main/java/katecam/hyuswim/user/exception/UserNotFoundException.java
  src/main/java/katecam/hyuswim/user/jwt/JwtUtil.java
  src/main/java/katecam/hyuswim/user/repository/UserRepository.java
  src/main/java/katecam/hyuswim/user/service/UserService.java
  src/test/java/katecam/hyuswim/HyuswimApplicationTests.java
Labels: chore

#50 refactor: 로그인 에러 코드 변수명을 LOGIN_FAILED로 변경
  src/main/java/katecam/hyuswim/common/error/ErrorCode.java
  src/main/java/katecam/hyuswim/user/service/UserService.java
Labels: refactor

#62 [Feat] 관리자 페이지 - 유저 제재 기능 추가 (조회/차단/해제/영구 차단)
  src/main/java/katecam/hyuswim/admin/controller/AdminController.java
  src/main/java/katecam/hyuswim/admin/controller/AdminUserController.java
  src/main/java/katecam/hyuswim/admin/dto/BlockRequest.java
  src/main/java/katecam/hyuswim/admin/dto/BlockResponse.java
  src/main/java/katecam/hyuswim/admin/dto/UserResponse.java
  src/main/java/katecam/hyuswim/admin/service/AdminUserService.java
  src/main/java/katecam/hyuswim/comment/repository/CommentRepository.java
  src/main/java/katecam/hyuswim/comment/service/CommentService.java
  src/main/java/katecam/hyuswim/post/repository/PostRepository.java
  src/main/java/katecam/hyuswim/report/service/ReportService.java
  src/main/java/katecam/hyuswim/user/User.java
  src/main/java/katecam/hyuswim/user/UserStatus.java
  src/main/resources/templates/admin/admin_dashboard.html
Labels: feature

#65 feat : 게시글 좋아요 기능 구현
  src/main/java/katecam/hyuswim/common/error/ErrorCode.java
  src/main/java/katecam/hyuswim/like/controller/PostLikeController.java
  src/main/java/katecam/hyuswim/like/domain/PostLike.java
  src/main/java/katecam/hyuswim/like/repository/PostLikeRepository.java
  src/main/java/katecam/hyuswim/like/service/PostLikeService.java
  src/main/java/katecam/hyuswim/post/domain/Post.java
  src/main/java/katecam/hyuswim/post/dto/PostDetailResponse.java
  src/main/java/katecam/hyuswim/post/dto/PostListResponse.java
Labels: feature

#80 refactor: JWT 기반 인증 구조 개선 및 @LoginUser 적용
  src/main/java/katecam/hyuswim/auth/config/LocalSecurityConfig.java
  src/main/java/katecam/hyuswim/auth/config/WebConfig.java
  src/main/java/katecam/hyuswim/auth/jwt/JwtFilter.java
  src/main/java/katecam/hyuswim/auth/jwt/JwtTokenRequest.java
  src/main/java/katecam/hyuswim/auth/jwt/JwtUtil.java
  src/main/java/katecam/hyuswim/auth/login/LoginUserArgumentResolver.java
  src/main/java/katecam/hyuswim/auth/principal/UserPrincipal.java
  src/main/java/katecam/hyuswim/comment/controller/CommentController.java
  src/main/java/katecam/hyuswim/comment/service/CommentService.java
  src/main/java/katecam/hyuswim/like/controller/PostLikeController.java
  src/main/java/katecam/hyuswim/like/service/PostLikeService.java
  src/main/java/katecam/hyuswim/post/controller/PostController.java
  src/main/java/katecam/hyuswim/post/domain/Post.java
  src/main/java/katecam/hyuswim/post/service/PostService.java
  src/main/java/katecam/hyuswim/report/Contoroller/ReportController.java
  src/main/java/katecam/hyuswim/report/service/ReportService.java
  src/main/java/katecam/hyuswim/user/service/UserService.java
Labels: bug, refactor

#97 [Refactor] deploy.yml 코드 스타일 검증 제거
  .github/workflows/deploy.yml
  env.example
  src/main/resources/application-dev.yml
Labels: refactor

#98 [Refactor] 관리자 페이지 - 사용자 제재 리팩토링
  src/main/java/katecam/hyuswim/admin/controller/AdminController.java
  src/main/java/katecam/hyuswim/admin/controller/AdminUserController.java
  src/main/java/katecam/hyuswim/admin/dto/BlockResponse.java
  src/main/java/katecam/hyuswim/admin/dto/UserDetailResponse.java
  src/main/java/katecam/hyuswim/admin/dto/UserListResponse.java
  src/main/java/katecam/hyuswim/admin/dto/UserResponse.java
  src/main/java/katecam/hyuswim/admin/service/AdminUserService.java
  src/main/java/katecam/hyuswim/auth/config/LocalSecurityConfig.java
Labels: refactor

#101 [Fix] 빌드 시 코드 스타일 미검증
  build.gradle
Labels: bug

#109 feat : 대댓글 기능 추가
  src/main/java/katecam/hyuswim/admin/service/AdminUserService.java
  src/main/java/katecam/hyuswim/comment/controller/CommentController.java
  src/main/java/katecam/hyuswim/comment/domain/Comment.java
  src/main/java/katecam/hyuswim/comment/dto/CommentDetailResponse.java
  src/main/java/katecam/hyuswim/comment/dto/CommentListResponse.java
  src/main/java/katecam/hyuswim/comment/dto/CommentRequest.java
  src/main/java/katecam/hyuswim/comment/dto/CommentTreeResponse.java
  src/main/java/katecam/hyuswim/comment/repository/CommentRepository.java
  src/main/java/katecam/hyuswim/comment/service/CommentService.java
  src/main/java/katecam/hyuswim/common/error/ErrorCode.java
Labels: feature

#112 refactor : ReportService 및 PostCategory 개선
  src/main/java/katecam/hyuswim/common/error/ErrorCode.java
  src/main/java/katecam/hyuswim/post/domain/PostCategory.java
  src/main/java/katecam/hyuswim/report/service/ReportService.java
Labels: refactor

#116 feat: 닉네임,자기소개 변경 api 구현
  src/main/java/katecam/hyuswim/common/error/ErrorCode.java
  src/main/java/katecam/hyuswim/user/User.java
  src/main/java/katecam/hyuswim/user/controller/MyPageController.java
  src/main/java/katecam/hyuswim/user/controller/UserController.java
  src/main/java/katecam/hyuswim/user/dto/SignupRequest.java
  src/main/java/katecam/hyuswim/user/dto/mypage/ProfileUpdate.java
  src/main/java/katecam/hyuswim/user/service/MyPageService.java
  src/main/java/katecam/hyuswim/user/service/UserService.java
Labels: feature

#149 feat : DevSecurity에 CROS 설정 추가
  .env.example
  .github/workflows/deploy.yml
  src/main/java/katecam/hyuswim/HyuswimApplication.java
  src/main/java/katecam/hyuswim/auth/config/AppProperties.java
  src/main/java/katecam/hyuswim/auth/config/DevSecurityConfig.java
  src/main/resources/application.yml
Labels: feature

#153 [Feat] 관리자 페이지 신고 조회
  src/main/java/katecam/hyuswim/admin/controller/AdminReportController.java
  src/main/java/katecam/hyuswim/admin/service/AdminReportService.java
  src/main/java/katecam/hyuswim/common/error/ErrorCode.java
  src/main/java/katecam/hyuswim/report/domain/Report.java
Labels: feature

#158 feat : 게시글 상세조회 시 조회수 1 증가 구현
  src/main/java/katecam/hyuswim/post/domain/Post.java
  src/main/java/katecam/hyuswim/post/service/PostService.java
Labels: feature

#161 refactor: PostCategory 응답에서 UI 전용 ALL 제거
  src/main/java/katecam/hyuswim/mission/MissionCategory.java
  src/main/java/katecam/hyuswim/post/domain/PostCategory.java
Labels: refactor

#164 fix : AI 계정 provider local로 설정
  src/main/java/katecam/hyuswim/user/domain/User.java
Labels: bug

#162 [Feat] 관리자 페이지 게시글 기능
  src/main/java/katecam/hyuswim/admin/controller/AdminPostController.java
  src/main/java/katecam/hyuswim/admin/controller/AdminReportController.java
  src/main/java/katecam/hyuswim/admin/controller/AdminUserController.java
  src/main/java/katecam/hyuswim/admin/dto/AdminPostDetailResponse.java
  src/main/java/katecam/hyuswim/admin/dto/AdminPostListResponse.java
  src/main/java/katecam/hyuswim/admin/service/AdminPostService.java
  src/main/java/katecam/hyuswim/admin/service/AdminReportService.java
  src/main/java/katecam/hyuswim/auth/config/LocalSecurityConfig.java
  src/main/java/katecam/hyuswim/user/domain/User.java
  src/main/resources/templates/admin/admin_dashboard.html
  src/main/resources/templates/admin/layout.html
  src/main/resources/templates/admin/posts/detail.html
  src/main/resources/templates/admin/posts/list.html
  src/main/resources/templates/admin/reports.html
  src/main/resources/templates/admin/reports/detail.html
  src/main/resources/templates/admin/reports/list.html
  src/main/resources/templates/admin/users.html
Labels: feature

#171 chore: GitHub Actions 워크플로우 YAML 문법 검사 제거
  .github/workflows/lint-workflows.yml
Labels: chore

#179 [Feat] mission 취소 기능/ 포인트 지급
  src/main/java/katecam/hyuswim/mission/controller/MissionController.java
  src/main/java/katecam/hyuswim/mission/repository/MissionProgressRepository.java
  src/main/java/katecam/hyuswim/mission/service/MissionService.java
  src/main/java/katecam/hyuswim/user/domain/User.java
  src/main/resources/templates/missions/list.html
Labels: feature

#201 feat: 게시글 전체 개수 반환 구현
  .env.example
  src/main/java/katecam/hyuswim/post/controller/PostStatController.java
  src/main/java/katecam/hyuswim/post/dto/PostCountResponse.java
  src/main/java/katecam/hyuswim/post/service/PostStatService.java
  src/main/resources/application-local.yml
Labels: feature

#203 [Feat] 지원 사업 관리 기능 구현
  src/main/java/katecam/hyuswim/admin/controller/AdminSupportController.java
  src/main/java/katecam/hyuswim/admin/service/AdminSupportService.java
  src/main/java/katecam/hyuswim/support/controller/SupportController.java
  src/main/java/katecam/hyuswim/support/domain/Support.java
  src/main/java/katecam/hyuswim/support/domain/SupportType.java
  src/main/java/katecam/hyuswim/support/dto/SupportDetailResponse.java
  src/main/java/katecam/hyuswim/support/dto/SupportResponse.java
  src/main/java/katecam/hyuswim/support/repository/SupportRepository.java
  src/main/java/katecam/hyuswim/support/service/SupportService.java
Labels: feature

#206 feat: redis로 이메일 인증 구현
  .env.example
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/katecam/hyuswim/auth/controller/AuthEmailController.java
  src/main/java/katecam/hyuswim/auth/dto/EmailResponse.java
  src/main/java/katecam/hyuswim/auth/dto/EmailSendRequest.java
  src/main/java/katecam/hyuswim/auth/dto/EmailVerifyRequest.java
  src/main/java/katecam/hyuswim/auth/service/AuthEmailService.java
  src/main/java/katecam/hyuswim/auth/service/EmailSenderService.java
  src/main/java/katecam/hyuswim/common/config/DevSecurityConfig.java
  src/main/java/katecam/hyuswim/common/config/LocalSecurityConfig.java
  src/main/java/katecam/hyuswim/common/config/RedisConfig.java
  src/main/java/katecam/hyuswim/common/error/ErrorCode.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: feature

#212 feat: 알림 조회/읽음/삭제 기능 구현
  src/main/java/katecam/hyuswim/auth/annotation/LoginUser.java
  src/main/java/katecam/hyuswim/auth/filter/JwtFilter.java
  src/main/java/katecam/hyuswim/auth/resolver/LoginUserArgumentResolver.java
  src/main/java/katecam/hyuswim/challenge/controller/ChallengeController.java
  src/main/java/katecam/hyuswim/comment/controller/CommentController.java
  src/main/java/katecam/hyuswim/common/config/DevSecurityConfig.java
  src/main/java/katecam/hyuswim/common/config/LocalSecurityConfig.java
  src/main/java/katecam/hyuswim/common/config/WebConfig.java
  src/main/java/katecam/hyuswim/common/error/ErrorCode.java
  src/main/java/katecam/hyuswim/like/controller/PostLikeController.java
  src/main/java/katecam/hyuswim/mission/controller/MissionController.java
  src/main/java/katecam/hyuswim/notification/NotiType.java
  src/main/java/katecam/hyuswim/notification/Notification.java
  src/main/java/katecam/hyuswim/notification/controller/NotificationController.java
  src/main/java/katecam/hyuswim/notification/domain/NotiType.java
  src/main/java/katecam/hyuswim/notification/domain/Notification.java
  src/main/java/katecam/hyuswim/notification/domain/TargetType.java
  src/main/java/katecam/hyuswim/notification/dto/NotificationReadRequest.java
  src/main/java/katecam/hyuswim/notification/dto/NotificationResponse.java
  src/main/java/katecam/hyuswim/notification/repository/NotificationRepository.java
  src/main/java/katecam/hyuswim/notification/service/NotificationService.java
  src/main/java/katecam/hyuswim/post/controller/PostController.java
  src/main/java/katecam/hyuswim/report/contoroller/ReportController.java
  src/main/java/katecam/hyuswim/user/controller/MyPageController.java
  src/main/java/katecam/hyuswim/user/controller/UserController.java
Labels: feature

#215 fix(cicd): MySQL 8.0 접속 오류 해결을 위한 allowPublicKeyRetrieval 옵션 추가
  .github/workflows/deploy.yml
Labels: bug

#217 fix: FRONTEND_URL Secrets 값 누락 방지를 위한 따옴표 감싸기 적용
  .github/workflows/deploy.yml
Labels: chore

#219 fix: AppProperties가 빈으로 등록되지 않던 문제 해결
  src/main/java/katecam/hyuswim/common/config/AppProperties.java
Labels: bug

#221 [Fix] application-dev 및 deploy.yml 수정
  .github/workflows/deploy.yml
  src/main/resources/application-dev.yml
Labels: bug

#225 [Fix] Github action 시크릿키 수정
  docker-compose.yml
Labels: bug

#227 [Refactor] 레디스 포트 환경변수 중복 주입 제거
  .github/workflows/deploy.yml
  docker-compose.yml
Labels: bug

#228 chore: 개발 서버 db를 mysql docker로 변경
  .env.example
  .github/workflows/deploy.yml
  docker-compose.yml
  src/main/java/katecam/hyuswim/common/config/AppProperties.java
  src/main/java/katecam/hyuswim/notification/controller/NotificationController.java
  src/main/java/katecam/hyuswim/notification/domain/Notification.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: chore

#230 fix: 배포 파이프라인에서 최신 JAR 파일만 업로드하도록 수정
  .github/workflows/deploy.yml
Labels: bug

#232 fix: deploy.yml 공백 제거 및 파일 전송 오류 수정
  .github/workflows/deploy.yml
Labels: bug

#234 fix: 다중 파일 전송 시 source 설정 오류 수정
  .github/workflows/deploy.yml
Labels: bug

#235 fix: scp-action tar 에러 해결 위해 ssh-action + scp로 교체
  .github/workflows/deploy.yml
Labels: bug

#237 chore: deploy.yml의 SCP 파일 전송 오류 해결 및 CI/CD 구조 개선
  .github/workflows/deploy.yml
Labels: bug

#238 feat: Spring Boot 애플리케이션을 Docker Compose 환경에 통합
  .env.example
  .github/workflows/deploy.yml
  .gitignore
  Dockerfile
  docker-compose.yml
Labels: feature

#240 ci: EC2 배포 워크플로우에 .env 주입 단계 추가
  .github/workflows/deploy.yml
Labels: bug, chore

#241 ci: GitHub Secrets 주입 방식 수정 및 .env 자동 삭제 적용
  .github/workflows/deploy.yml
Labels: bug, chore

#242 ci: 배포 시 Gradle 빌드 및 Docker Compose 실행 자동화
  .github/workflows/deploy.yml
Labels: chore

#243 fix: JwtUtil 중복 Bean 충돌 해결 및 빌드 캐시 정리
  .env.example
Labels: bug

#244 fix: AppProperties 바인딩 오류 수정
  src/main/java/katecam/hyuswim/common/config/AppProperties.java
Labels: bug

#247 ci: EC2 배포 시 Gradle 빌드 제거 후 Docker Compose만 실행하도록 수정
  .github/workflows/deploy.yml
  .gitignore
  docker-compose.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: chore

#248 chore: deploy.yml 에서 .env.dev에서 .dev 제거
  .github/workflows/deploy.yml
Labels: chore

#250 ci: 배포 시 scp 대신 rsync 사용하여 잔여 파일 문제 해결
  .dockerignore
  .github/workflows/deploy.yml
  docker-compose.yml
Labels: chore

#254 fix: 환경변수 매핑 개선: APP_PORT와 SPRING_PROFILE 적용
  src/main/resources/application.yml
Labels: bug
